version: "3"

services:
  app:
    container_name: react-starter
    build: .
    command: yarn dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    networks:
      - default
      - api
    env_file: .env

networks:
  api:
    external:
      name: api_proxy

volumes:
  node_modules:
